# Perzeptron-Lernalgorithmus

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
from ipywidgets import interact
from IPython.display import display

In [2]:
data = np.array([[-3, 1, -1], 
                 [-3, 3, 1], 
                 [-2, 1, -1], 
                 [-2, 4, 1], 
                 [-1, 3, 1], 
                 [-1, 4, 1], 
                 [2, 2, -1], 
                 [2, 4, 1], 
                 [3, 2, -1], 
                 [4, 1, -1]])
data.shape

(10, 3)

## Teil 1: Implementierung

In [44]:
def w(pp,weight):
    res=0
    for i in range(len(pp)):
        res+=pp[i]*weight[i]
    return (res>0)

def newW(weight,eta,pp):
    for i in range(len(pp)):
        weight[i]+=eta*pp[i]
    return weight

weight_vector = np.zeros(3, dtype=np.float32)
weight_vectors = []
eta = 1
change = True

while change:
    change = False
    for p in data:
        if (p[2]==1) & (w(p,weight_vector)==False):
            weight_vector=newW(weight_vector,eta,p)
            change = True
        elif (p[2]==-1) & w(p,weight_vector):
            weight_vector = newW(weight_vector, -eta, p)
            change = True
        #print (weight_vector)
        weight_vectors.append(weight_vector)

[0. 0. 0.]
[-3.  3.  1.]
[-1.  2.  2.]
[-1.  2.  2.]
[-1.  2.  2.]
[-1.  2.  2.]
[-1.  2.  2.]
[-1.  2.  2.]
[-1.  2.  2.]
[-1.  2.  2.]
[2. 1. 3.]
[-1.  4.  4.]
[1. 3. 5.]
[1. 3. 5.]
[1. 3. 5.]
[1. 3. 5.]
[-1.  1.  6.]
[-1.  1.  6.]
[-1.  1.  6.]
[-1.  1.  6.]
[-1.  1.  6.]
[-1.  1.  6.]
[-1.  1.  6.]
[-1.  1.  6.]
[-1.  1.  6.]
[-1.  1.  6.]
[-1.  1.  6.]
[-1.  1.  6.]
[-1.  1.  6.]
[-1.  1.  6.]


## Teil 2: Darstellung

In [63]:
def plot_vectors(index):
    fig = plt.figure(figsize=(7, 7))
    sub1 = fig.add_subplot(221)
    sub1.plot(weight_vectors[index])
    sub1.set_title('Perceptron Learning Algorithm')
    plt.show()     
        
interact(plot_vectors, index = widgets.IntSlider(min=0,max=len(weight_vectors)-1,step=1,value=0))


#axamp = plt.axes()
#samp = widgets.IntSlider()
#plt.plot(weight_vector)
#plt.show()

interactive(children=(IntSlider(value=0, description='index', max=29), Output()), _dom_classes=('widget-intera…

<function __main__.plot_vectors(index)>